title: "My Engineering Portfolio"
description: "A portfolio showcasing my 3 years of studies."
baseurl: ""
url: "https://saad-benj.github.io" # URL GitHub Pages
author:
  name: "Saad Benj"
  email: "email@example.com"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
# Navigation 
nav:
  - title: "Welcome"
    url: /
  - title: "Engineering Course"
    url: /engineering-course/
    children:
      - title: "Projects"
        url: /engineering-course/projects/
      - title: "Productions"
        url: /engineering-course/productions/
  - title: "International Mobility"
    url: /international-mobility/
    children:
      - title: "PCE"
        url: /international-mobility/pce/
      - title: "LV2"
        url: /international-mobility/lv2/
  - title: "Sustainability & Civic Engagement"
    url: /sustainability-civic-engagement/
  - title: "Sport & Other Activities"
    url: /sport-other-activities/
  - title: "Career Development"
    url: /career-development/
    children:
      - title: "Internships"
        url: /career-development/internships/
      - title: "PEP"
        url: /career-development/pep/
